[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["pywaybackup"]

[project]
name = "pywaybackup"
version = "3.0.1"
description = "Query and download archive.org as simple as possible."
authors = [
    { name = "bitdruid", email = "bitdruid@outlook.com" }
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests==2.31.0",
    "tqdm==4.66.2",
    "python-magic==0.4.27; sys_platform == 'linux'",
    "python-magic-bin==0.4.14; sys_platform == 'win32'",
]

[project.scripts]
waybackup = "pywaybackup.main:main"

[project.urls]
homepage = "https://github.com/bitdruid/python-wayback-machine-downloader"